Fix missing SDSS define
per @Spawn32
Fix to zero-padded pin naming

Marlin/src/sd/../inc/../pins/pins_MKS_SBASE.h:187:28: error: 'P0_6' was not declared in this scope
#define SDSS               P0_6