ExtUI::onSetPowerLoss onoff not defined use enabled
Compile error,
Marlin/src/feature/powerloss.cpp:116:46: error: 'onoff' was not declared in this scope

Use enabled which is set from onoff in PrintJobRecovery::enable().