Prevent undefined lcd_tmpfan_speed on NO_LCD_MENUS
This fixes a build error introduced by 082f6a2 when NO_LCD_MENUS
is uncommented:

 Marlin/src/module/temperature.cpp: In static member function
 'static void Temperature::set_fan_speed(uint8_t, uint16_t)':
 Marlin/src/module/temperature.cpp:168:7: error: 'lcd_tmpfan_speed'
 was not declared in this scope

Given that ENABLED(ULTRA_LCD) is always true when HAS_LCD_MENU
is also true,

 #if ENABLED(ULTIPANEL)
   ...
   #define ULTRA_LCD
 #endif
 ...
 #define HAS_LCD_MENU  (ENABLED(ULTIPANEL) && DISABLED(NO_LCD_MENUS))

this shouldn't change the logic other than fixing the build error.

Fixes #12993.

Signed-off-by: Jiri Jaburek <comps@nomail.dom>