Fix automatic upload port selection for LPC1768 on Darwin and Linux
Following <https://github.com/MarlinFirmware/Marlin/pull/24574>, automatic upload port stopped working. Instead, you just get the error:

```
Looking for upload disk...
Error: Please specify `upload_port` for environment or use global `--upload-port` option.
```

This is due to the default `__str__` behaviour of `Pathlib.Path` producing the full path, so we need to keep the `filenames` concept. Otherwise, the target drive cannot be found automatically. (Alternately, the filename check could become `any(target_filename == x.name for x in files)`.

I also made the loop-termination logic on MacOS the same as Linux, and unified the `is_dir()` and `is_file()` checks between the two.

Tested on MacOS.

Tabs preserved to match existing code.