Fix undefined init_tmc_section on NO_LCD_MENUS
Marlin/src/lcd/ultralcd.cpp: In static member function
'static void MarlinUI::init()':
Marlin/src/lcd/ultralcd.cpp:264:22: error: 'init_tmc_section'
was not declared in this scope

Looking at other usages of init_tmc_section, it seems that
init_tmc_section is defined and should be called only when
HAS_LCD_MENU is defined.

Signed-off-by: Jiri Jaburek <comps@nomail.dom>