Removes inline comments from BEEPER_PIN #define due to FastIO issues
Inline comments on the BEEPER_PINT was causing the compiler to barf:
pins_RAMPS_14.h:221: error: pasting "/* Beeper on AUX-4*/" and "_RPORT"
does not give a valid preprocessing token