Makefile: Add Tone.cpp to the CXX source files
Tone.cpp (from ADRUINO_DIR/hardware/arduino/avr/cores/arduino/) is required when
the speaker function is enabled. Otherwise, the linker complains:

applet/src/libs/buzzer.o: In function `Buzzer::tick()':
buzzer.cpp:(.text._ZN6Buzzer4tickEv+0xb2): undefined reference to
	`tone(unsigned char, unsigned int, unsigned long)'
collect2: error: ld returned 1 exit status