resolve issue " invalid conversion from ‘const char*’ to ‘char*’" without needing -fpermissive
Resolves compile issue:

ultralcd.cpp: In function ‘void lcd_enqueue_filament_change(uint8_t)’:
ultralcd.cpp:1264:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
           case 0: command_M600 = PSTR("M600 B0 T0"); break;
                                  ^
ultralcd.cpp:1265:34: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
           case 1: command_M600 = PSTR("M600 B0 T1"); break;
                                  ^
PSTR is defined as:
#define PSTR(s) \
	((const PROGMEM char *)(s))

trying a cast  to (char *)