ultralcd.cpp
When compiling with the SCARA Configuration.h this compilation error occurs:

ultralcd.cpp:1805: undefined reference to `menu_action_setting_edit_float74(char const*, float*, float, float)'

Two options:
1) Create the float74 formatting/menu defines/code.  Not sure the intent of the float74 - is it a typo or does the scale factor need that much precision?

2) Switch the float74 to float52.  This solves the compilation problem, but does it miss the intent of the original author?

I still need to check how this item looks on the lcd.  At present just interested in making it compile.